### ISSUE TITLE
Unable to find entrypoint.sh

### ISSUE THREAD

**Issue by adamzimmermann** [ibiqlik/action-yamllint#13]
First off, thank you for creating this action. It's amazing how simple and valuable it is to add this to our workflows to keep ourselves accountable.

We are trying to update to the latest version of this action and seeing this:
```
Run ibiqlik/action-yamllint@v3
  with:
    config_file: .yamllint.yml
    format: github
    strict: false
/__w/_temp/5dd290ab-796c-4f22-9b66-6cb663b9c81b.sh: line 1: /home/runner/work/_actions/ibiqlik/action-yamllint/v3/entrypoint.sh: No such file or directory
Error: Process completed with exit code 127.
```

This is our configuration.
```
- name: YAML Lint
  uses: ibiqlik/action-yamllint@v3
  with:
    config_file: .yamllint.yml
```

Any ideas on what we are missing or doing wrong? 🤞🏼
