### ISSUE TITLE
GitHub Action Output doesn't have YAML file paths the problems refer to.

### ISSUE THREAD

**Issue by jgstew** [ibiqlik/action-yamllint#14]
The errors and warnings output in the GitHub Action don't show which file path they are for, but I have 4 different YAML files in my repo. Is there a way to configure this?

My config: https://github.com/jgstew/jgstew-recipes/blob/main/.github/workflows/yamllint.yaml

```
name: YAML Lint

on:
  push:
    paths: 
    - "**.yaml"
    - "**.yml"
  pull_request:
    paths:
    - "**.yaml"
    - "**.yml"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: GitHub YAMLlint
      uses: ibiqlik/action-yamllint@v3
```

Example output with warnings / errors but no paths: https://github.com/jgstew/jgstew-recipes/actions/runs/636513923

**Comment by jgstew** [comment]
Seems like this might be a bug in the output format not being set as `github` properly here:

https://github.com/adrienverge/yamllint/blob/8eebab68ab31138c7ef021117897f71fb537b747/yamllint/cli.py#L115

Specifically here:

```
        elif args_format == 'github' or (args_format == 'auto' and
                                         'GITHUB_ACTIONS' in os.environ and
                                         'GITHUB_WORKFLOW' in os.environ):
```

Seems like maybe it should be:

```
        elif args_format == 'github' or (args_format == 'auto' and
                                         ('GITHUB_ACTIONS' in os.environ or
                                         'GITHUB_WORKFLOW' in os.environ)):
```

but that is just a guess on my part.

**Comment by jgstew** [comment]
Seems like a fix would be to use a more generic GitHub action as outlined here:

https://github.com/adrienverge/yamllint/blob/master/docs/integration.rst

**Comment by jgstew** [comment]
I now see that "github" should be the default format and it is configurable here: https://github.com/ibiqlik/action-yamllint/blob/master/action.yml#L16

**Comment by ibiqlik** [comment]
@jgstew Sorry for late reply, notification overflow.

As you found out yourself you can set your desired output format in the action
```yaml
    - uses: ibiqlik/action-yamllint@v3
      with:
        format: parsable
```
