### ISSUE TITLE
No file information in output

### ISSUE THREAD

**Issue by thoraage** [ibiqlik/action-yamllint#16]
I'm trying to validate my yaml with this configuration:

```
name: Validation
on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Linting yaml
        uses: ibiqlik/action-yamllint@v3
        with:
          config_data: relaxed
```

... but I don't get any information about which files. Is this an error? I get the information fine when running locally.

![image](https://user-images.githubusercontent.com/27269/115846365-1d28f980-a422-11eb-95c0-53349594123a.png)
