### ISSUE TITLE
Multiple config in single .yamllint.yml file

### ISSUE THREAD

**Issue by syedimranhassan** [ibiqlik/action-yamllint#18]
Can we specify multiple configs in a single config_file? 
Like we have multiple jobs which are using different configuration and we need to specify those configs in config_file.
That would be awesome if we specify multiple configs in a single file and use them in jobs.
We can specify some thing like this
`config_file: .yamllint.yml <key_in_yaml>`

or will have some key like 
 `config_key:  <key_in_yaml>`

**Comment by ibiqlik** [comment]
If I understood your question correctly, you want a single yamllint config file which has multiple separate configuration and be able to just a specific configuration by referencing a key. In that case it's not possible, this action is basically a wrapper for `yamllint` and uses configuration provided by it https://yamllint.readthedocs.io/en/stable/configuration.html#

This could be achievable in this action though by implementing a logic that extracts the config and passes it to yamllint as `--config-data`.

A suggestion would be for you to create a folder `.yamllint_configs` with multiple config files and then reference those in jobs, for example:

```
jobs:
  job1:
    steps:
    - uses: ibiqlik/action-yamllint@v3
      with:
        config_file: .yamllint_configs/yamlconfig1
  job2:
    steps:
    - uses: ibiqlik/action-yamllint@v3
      with:
        config_file: .yamllint_configs/yamlconfig2
```
