### ISSUE TITLE
Example GitHub Action does not pass yamllint checks

### ISSUE THREAD

**Issue by tchupp** [ibiqlik/action-yamllint#24]
On this page there is the example: https://github.com/marketplace/actions/yaml-lint
```yaml
name: Yaml Lint
on: [push]
jobs:
  lintAllTheThings:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: yaml-lint
      uses: ibiqlik/action-yamllint@v3
```

When I add that to my project, the github action fails with the following error.
```bash
$ yamllint .
./.github/workflows/yaml-lint.yml
  2:1       warning  truthy value should be one of [false, true]  (truthy)
```

Based on [this documentation](https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.truthy), it suggests that the key `on: ` is being flagged as a boolean that needs correcting.
