### ISSUE TITLE
yamllint: command not found

### ISSUE THREAD

**Issue by till** [ibiqlik/action-yamllint#37]
Running your action with `act` currently produces:

```
[ci/helm-lint]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/5-composite-yamllint.sh] user= workdir=
| ======================
| = Linting YAML files =
| ======================
| /var/run/act/actions/ibiqlik-action-yamllint@v3.1.1/entrypoint.sh: line 34: yamllint: command not found
```

This is how I use it:

```yaml
---
name: ci

on:
  pull_request

jobs:
  helm-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ibiqlik/action-yamllint@v3.1.1
        with:
          format: github
          file_or_dir: |
            certmanager
            certmanager-config
            cloudnative-pg
            haproxy-ingress
            postgresql
```

**Comment by sakulali** [comment]
I found the same problem when use [act](https://github.com/nektos/act) for local ci test.
![7c2984fa-f698-49d1-a2b6-71dbaa68d2fc](https://user-images.githubusercontent.com/3955787/218296988-f48de47c-5acf-4cfe-b222-48087c866424.jpeg)
Part of my workflows job show:
```
yamllint-checker:
    needs: changes
    if: |
      (needs.changes.outputs.yaml == 'true')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Yamllint checker
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: samples/deploy 
          config_file: .yamllint.yml 
```

**Comment by till** [comment]
I just looked at the action, it seems it doesn't actually install yamllint? I am a bit confused.

**Comment by ReenigneArcher** [comment]
I'm facing the same issue in a self hosted runner. I was under the impression this was a docker action (https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action), but it appears to be a composite action which only runs the `entrypoint.sh`...

Looks like versions prior to v3 might work. https://github.com/ibiqlik/action-yamllint/releases/tag/v3.0.0

Perhaps the action should verify that `yamllint` is installed? And if not, install it into a `venv` that is then destroyed.

I will take a stab at this improvement. If it wouldn't be accepted, please let me know though so I don't waste my time.

**Comment by atkinsonm** [comment]
I was able to fork this repository and fix it for myself by modifying `action.yml` to replace

```yml
using: 'composite'
steps:
    - run: ${{ github.action_path }}/entrypoint.sh
      shell: bash
      env:
        INPUT_FILE_OR_DIR: ${{ inputs.file_or_dir }}
        INPUT_CONFIG_FILE: ${{ inputs.config_file }}
        INPUT_CONFIG_DATA: ${{ inputs.config_data }}
        INPUT_FORMAT: ${{ inputs.format }}
        INPUT_STRICT: ${{ inputs.strict }}
```

with 

```yml
using: 'docker'
image: 'Dockerfile'
```

If this has no other unwanted side effects, I would like to see this fixed upstream.
